### PR TITLE
A few improvements

### PR DESCRIPTION
**Pull request by dotdoom**

### CODE REVIEW

**Comment by ghost** [comment]
I successfully tested everything, but the element selector does not work:
```python
Traceback (most recent call last):
  File "/home/sebastian/dev/python-webkit2png/webkit2png/scripts.py", line 206, in __main_qt
    renderer.render_to_file(res=options.url, file_object=options.output)
  File "/home/sebastian/dev/python-webkit2png/webkit2png/webkit2png.py", line 115, in render_to_file
    image = self.render(res)
  File "/home/sebastian/dev/python-webkit2png/webkit2png/webkit2png.py", line 100, in render
    image = helper.render(res)
  File "/home/sebastian/dev/python-webkit2png/webkit2png/webkit2png.py", line 263, in render
    self._page.mainFrame().documentElement())
TypeError: 'str' object is not callable
```
The rest works fine!

**Comment by dotdoom** [comment]
The `elementSelector` supplied must be a lambda of `(document) -> (element, size)`. I guess you supplied a jQuery selector, which could also be interesting to implement.

**Comment by ghost** [comment]
@dotdoom could you please add documentation along with an example? that would be helpful I think

**Comment by dotdoom** [comment]
@wagner-certat that would certainly be on my radar but I won't have cycles to get to it soon. In case you're interested here's one real life example:
https://github.com/dotdoom/comicsbot/blob/b52502a861d673760050b6ea36bdf7cc3ad0f82c/render.py#L119

For that project I had to switch from QtWebKit to QWebEngine (Chromium) eventually, because the latter has much better support for the latest CSS and HTML features: https://github.com/dotdoom/comicsbot/blob/master/web2png.py

**Comment by dotdoom** [comment]
I've switched to puppeteer meanwhile, closing this PR since I won't be able to follow up soon and it doesn't look to pick anyone else's interest.

**Pull request closed without merging**
